seed: 42
device: cuda:0
num_steps_per_env: 32
max_iterations: 500
empirical_normalization: null
obs_groups: {}
clip_actions: null
save_interval: 50
experiment_name: go2_flat_direct
run_name: ''
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: false
load_run: .*
load_checkpoint: model_.*.pt
class_name: OnPolicyRunner
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_obs_normalization: true
  critic_obs_normalization: true
  actor_hidden_dims:
  - 256
  - 128
  - 64
  critic_hidden_dims:
  - 256
  - 128
  - 64
  activation: elu
algorithm:
  class_name: PPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.0003
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.0
  desired_kl: 0.008
  max_grad_norm: 1.0
  value_loss_coef: 4.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  rnd_cfg: null
  symmetry_cfg: null
