viewer:
  eye: !!python/tuple
  - 7.5
  - 7.5
  - 7.5
  lookat: !!python/tuple
  - 0.0
  - 0.0
  - 0.0
  cam_prim_path: /OmniverseKit_Persp
  resolution: !!python/tuple
  - 1280
  - 720
  origin_type: world
  env_index: 0
  asset_name: null
  body_name: null
sim:
  physics_prim_path: /physicsScene
  device: cuda:0
  dt: 0.005
  render_interval: 4
  gravity: !!python/tuple
  - 0.0
  - 0.0
  - -9.81
  enable_scene_query_support: false
  use_fabric: true
  physx:
    solver_type: 1
    min_position_iteration_count: 1
    max_position_iteration_count: 255
    min_velocity_iteration_count: 0
    max_velocity_iteration_count: 255
    enable_ccd: false
    enable_stabilization: false
    enable_enhanced_determinism: false
    bounce_threshold_velocity: 0.5
    friction_offset_threshold: 0.04
    friction_correlation_distance: 0.025
    gpu_max_rigid_contact_count: 8388608
    gpu_max_rigid_patch_count: 163840
    gpu_found_lost_pairs_capacity: 2097152
    gpu_found_lost_aggregate_pairs_capacity: 33554432
    gpu_total_aggregate_pairs_capacity: 2097152
    gpu_collision_stack_size: 67108864
    gpu_heap_capacity: 67108864
    gpu_temp_buffer_capacity: 16777216
    gpu_max_num_partitions: 8
    gpu_max_soft_body_contacts: 1048576
    gpu_max_particle_contacts: 1048576
    solve_articulation_contact_last: false
  physics_material:
    func: isaaclab.sim.spawners.materials.physics_materials:spawn_rigid_body_material
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    friction_combine_mode: multiply
    restitution_combine_mode: multiply
    compliant_contact_stiffness: 0.0
    compliant_contact_damping: 0.0
  render:
    enable_translucency: null
    enable_reflections: null
    enable_global_illumination: null
    antialiasing_mode: null
    enable_dlssg: null
    enable_dl_denoiser: null
    dlss_mode: null
    enable_direct_lighting: null
    samples_per_pixel: null
    enable_shadows: null
    enable_ambient_occlusion: null
    dome_light_upper_lower_strategy: null
    carb_settings: null
    rendering_mode: null
  create_stage_in_memory: false
  logging_level: WARNING
  save_logs_to_file: true
ui_window_class_type: isaaclab.envs.ui.base_env_window:BaseEnvWindow
seed: 42
decimation: 4
is_finite_horizon: false
episode_length_s: 20.0
scene:
  num_envs: 4096
  env_spacing: 4.0
  lazy_sensor_update: true
  replicate_physics: true
  filter_collisions: true
  clone_in_fabric: false
events: null
observation_space: 52
num_observations: null
state_space: 0
num_states: null
observation_noise_model: null
action_space: 12
num_actions: null
action_noise_model: null
rerender_on_reset: false
num_rerenders_on_reset: 0
wait_for_textures: true
xr: null
log_dir: /workspace/isaaclab/logs/rsl_rl/go2_flat_direct/2025-12-18_14-57-01
robot_cfg:
  class_type: isaaclab.assets.articulation.articulation:Articulation
  prim_path: /World/envs/env_.*/Robot
  spawn:
    func: isaaclab.sim.spawners.from_files.from_files:spawn_from_usd
    visible: true
    semantic_tags: null
    copy_from_source: true
    mass_props: null
    deformable_props: null
    rigid_props:
      rigid_body_enabled: null
      kinematic_enabled: null
      disable_gravity: false
      linear_damping: 0.0
      angular_damping: 0.0
      max_linear_velocity: 1000.0
      max_angular_velocity: 1000.0
      max_depenetration_velocity: 1.0
      max_contact_impulse: null
      enable_gyroscopic_forces: null
      retain_accelerations: false
      solver_position_iteration_count: null
      solver_velocity_iteration_count: null
      sleep_threshold: null
      stabilization_threshold: null
    collision_props: null
    activate_contact_sensors: true
    scale: null
    articulation_props:
      articulation_enabled: null
      enabled_self_collisions: false
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      sleep_threshold: null
      stabilization_threshold: null
      fix_root_link: null
    fixed_tendons_props: null
    spatial_tendons_props: null
    joint_drive_props: null
    visual_material_path: material
    visual_material: null
    usd_path: https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.1/Isaac/IsaacLab/Robots/Unitree/Go2/go2.usd
    variants: null
  init_state:
    pos: !!python/tuple
    - 0.0
    - 0.0
    - 0.4
    rot: !!python/tuple
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    lin_vel: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    ang_vel: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    joint_pos:
      .*L_hip_joint: 0.1
      .*R_hip_joint: -0.1
      F[L,R]_thigh_joint: 0.8
      R[L,R]_thigh_joint: 1.0
      .*_calf_joint: -1.5
    joint_vel:
      .*: 0.0
  collision_group: 0
  debug_vis: false
  articulation_root_prim_path: null
  soft_joint_pos_limit_factor: 0.9
  actuators:
    base_legs:
      class_type: isaaclab.actuators.actuator_pd:ImplicitActuator
      joint_names_expr:
      - .*_hip_joint
      - .*_thigh_joint
      - .*_calf_joint
      effort_limit: 23.5
      velocity_limit: 30.0
      effort_limit_sim: null
      velocity_limit_sim: null
      stiffness: 0.0
      damping: 0.0
      armature: null
      friction: null
      dynamic_friction: null
      viscous_friction: null
  actuator_value_resolution_debug_print: false
contact_sensor:
  class_type: isaaclab.sensors.contact_sensor.contact_sensor:ContactSensor
  prim_path: /World/envs/env_.*/Robot/.*
  update_period: 0.005
  history_length: 3
  debug_vis: false
  track_pose: false
  track_contact_points: false
  max_contact_data_count_per_prim: 4
  track_air_time: true
  force_threshold: 1.0
  filter_prim_paths_expr: []
  visualizer_cfg:
    prim_path: /Visuals/ContactSensor
    markers:
      contact:
        func: isaaclab.sim.spawners.shapes.shapes:spawn_sphere
        visible: true
        semantic_tags: null
        copy_from_source: true
        mass_props: null
        rigid_props: null
        collision_props: null
        activate_contact_sensors: false
        visual_material_path: material
        visual_material:
          func: isaaclab.sim.spawners.materials.visual_materials:spawn_preview_surface
          diffuse_color: !!python/tuple
          - 1.0
          - 0.0
          - 0.0
          emissive_color: !!python/tuple
          - 0.0
          - 0.0
          - 0.0
          roughness: 0.5
          metallic: 0.0
          opacity: 1.0
        physics_material_path: material
        physics_material: null
        radius: 0.02
      no_contact:
        func: isaaclab.sim.spawners.shapes.shapes:spawn_sphere
        visible: false
        semantic_tags: null
        copy_from_source: true
        mass_props: null
        rigid_props: null
        collision_props: null
        activate_contact_sensors: false
        visual_material_path: material
        visual_material:
          func: isaaclab.sim.spawners.materials.visual_materials:spawn_preview_surface
          diffuse_color: !!python/tuple
          - 0.0
          - 1.0
          - 0.0
          emissive_color: !!python/tuple
          - 0.0
          - 0.0
          - 0.0
          roughness: 0.5
          metallic: 0.0
          opacity: 1.0
        physics_material_path: material
        physics_material: null
        radius: 0.02
goal_vel_visualizer_cfg:
  prim_path: /Visuals/Command/velocity_goal
  markers:
    arrow:
      func: isaaclab.sim.spawners.from_files.from_files:spawn_from_usd
      visible: true
      semantic_tags: null
      copy_from_source: true
      mass_props: null
      deformable_props: null
      rigid_props: null
      collision_props: null
      activate_contact_sensors: false
      scale: !!python/tuple
      - 0.5
      - 0.5
      - 0.5
      articulation_props: null
      fixed_tendons_props: null
      spatial_tendons_props: null
      joint_drive_props: null
      visual_material_path: material
      visual_material:
        func: isaaclab.sim.spawners.materials.visual_materials:spawn_preview_surface
        diffuse_color: !!python/tuple
        - 0.0
        - 1.0
        - 0.0
        emissive_color: !!python/tuple
        - 0.0
        - 0.0
        - 0.0
        roughness: 0.5
        metallic: 0.0
        opacity: 1.0
      usd_path: https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.1/Isaac/Props/UIElements/arrow_x.usd
      variants: null
current_vel_visualizer_cfg:
  prim_path: /Visuals/Command/velocity_current
  markers:
    arrow:
      func: isaaclab.sim.spawners.from_files.from_files:spawn_from_usd
      visible: true
      semantic_tags: null
      copy_from_source: true
      mass_props: null
      deformable_props: null
      rigid_props: null
      collision_props: null
      activate_contact_sensors: false
      scale: !!python/tuple
      - 0.5
      - 0.5
      - 0.5
      articulation_props: null
      fixed_tendons_props: null
      spatial_tendons_props: null
      joint_drive_props: null
      visual_material_path: material
      visual_material:
        func: isaaclab.sim.spawners.materials.visual_materials:spawn_preview_surface
        diffuse_color: !!python/tuple
        - 0.0
        - 0.0
        - 1.0
        emissive_color: !!python/tuple
        - 0.0
        - 0.0
        - 0.0
        roughness: 0.5
        metallic: 0.0
        opacity: 1.0
      usd_path: https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.1/Isaac/Props/UIElements/arrow_x.usd
      variants: null
action_scale: 0.25
debug_vis: true
Kp: 20.0
Kd: 0.5
torque_limits: 100.0
base_height_min: 0.2
terrain:
  class_type: isaaclab.terrains.terrain_importer:TerrainImporter
  collision_group: -1
  prim_path: /World/ground
  num_envs: 4096
  terrain_type: plane
  terrain_generator: null
  usd_path: null
  env_spacing: 4.0
  use_terrain_origins: true
  visual_material:
    func: isaaclab.sim.spawners.materials.visual_materials:spawn_preview_surface
    diffuse_color: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    emissive_color: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    roughness: 0.5
    metallic: 0.0
    opacity: 1.0
  physics_material:
    func: isaaclab.sim.spawners.materials.physics_materials:spawn_rigid_body_material
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    friction_combine_mode: multiply
    restitution_combine_mode: multiply
    compliant_contact_stiffness: 0.0
    compliant_contact_damping: 0.0
  max_init_terrain_level: null
  debug_vis: false
lin_vel_reward_scale: 1.0
yaw_rate_reward_scale: 0.5
action_rate_reward_scale: -0.1
raibert_heuristic_reward_scale: -10.0
feet_clearance_reward_scale: -30.0
tracking_contacts_shaped_force_reward_scale: 4.0
orient_reward_scale: -5.0
lin_vel_z_reward_scale: -0.02
dof_vel_reward_scale: -0.0001
ang_vel_xy_reward_scale: -0.001
